# Generated by Django 3.0.7 on 2020-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='owners_equity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Owners equity'),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='period',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('FY', 'FY')], default='Q1', max_length=2),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='period',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('FY', 'FY')], default='Q1', max_length=2),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='period',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('FY', 'FY')], default='Q1', max_length=2),
        ),
    ]
