# Generated by Django 3.0.7 on 2020-07-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20200627_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='long_term_loan_depts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Long-term loan and depts'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='short_term_loan_depts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Short-term loan and depts'),
        ),
    ]
