# Generated by Django 3.0.7 on 2020-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_chartcolour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomestatement',
            name='other_income',
        ),
        migrations.RemoveField(
            model_name='incomestatement',
            name='profit_after_corporate_income_tax_shares_holder',
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='net_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Net Income'),
        ),
    ]
